TestShelfCMAPP:
  mail:
    senduser: '676307573@qq.com'
    sendpswd: 'atcimddyfallbebb'
    receusers: 'yangxin@htyunwang.com'
  log:
      file_name: TestShelfCMAPP.log
      backup: 5
      console_level: WARNING
      file_level: DEBUG
      pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'